name: roomy
version: 1.1.3+1
publish_to: none
description: "roomy"
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  fluentui_system_icons: ^1.1.244
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  get: ^4.7.2
  get_cli: ^1.8.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  intl: ^0.18.1
  lottie: ^3.3.1
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  syncfusion_flutter_calendar: ^28.2.6

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/icon.png"
  web:
    generate: true
    image_path: "assets/logos/icon.png"

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/gifs/