// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC21P9Pz-upISUp0xS1_3QpakohxPA-w2o',
    appId: '1:685191567612:web:870232e9f503999cb2df79',
    messagingSenderId: '685191567612',
    projectId: 'roomy-ba',
    authDomain: 'roomy-ba.firebaseapp.com',
    storageBucket: 'roomy-ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhnzR59UTU9hWPTWOlmiYYunlM20SDkok',
    appId: '1:685191567612:android:7c12f730d4c3c98eb2df79',
    messagingSenderId: '685191567612',
    projectId: 'roomy-ba',
    storageBucket: 'roomy-ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmaSPM-VrVAdXvh2olZYHFJTFdutcDXB8',
    appId: '1:685191567612:ios:1d6048d2c0ea17dab2df79',
    messagingSenderId: '685191567612',
    projectId: 'roomy-ba',
    storageBucket: 'roomy-ba.firebasestorage.app',
    iosClientId: '685191567612-6lhpq7a3ubf3jms9i8v0p41f5s0pjnse.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomy',
  );
}
